# Generated by Django 2.1.7 on 2019-03-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.CharField(max_length=3)),
                ('school', models.TextField()),
                ('admission_no', models.IntegerField()),
                ('fullname', models.CharField(max_length=80)),
                ('f_name', models.CharField(max_length=80)),
                ('m_name', models.CharField(max_length=80)),
                ('goal', models.CharField(max_length=60)),
                ('address', models.TextField()),
                ('birth_date', models.DateTimeField()),
                ('blood_group', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=50)),
                ('social_links', models.CharField(max_length=200)),
                ('profile_pic_link', models.CharField(max_length=80)),
            ],
        ),
    ]
