# Generated by Django 2.1.7 on 2019-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial',
            field=models.AutoField(db_column='serial', primary_key=True, serialize=False),
        ),
    ]
